table Sellers
	lineageTag: a7ae1e0a-e1da-42c0-bf66-2198dfd4f02a

	column seller_id
		dataType: string
		lineageTag: bc1ac0cb-18d5-4092-b0eb-5376e03d786a
		summarizeBy: none
		sourceColumn: seller_id

		annotation SummarizationSetBy = Automatic

	column seller_zip_code_prefix
		dataType: int64
		formatString: 0
		lineageTag: a3ee3ed8-7975-466b-aa2d-8322f0bbce2f
		summarizeBy: none
		sourceColumn: seller_zip_code_prefix

		annotation SummarizationSetBy = Automatic

	column seller_city
		dataType: string
		lineageTag: 30559b40-5a0d-438f-bd75-7deb56873398
		summarizeBy: none
		sourceColumn: seller_city

		annotation SummarizationSetBy = Automatic

	column seller_state
		dataType: string
		lineageTag: 230f4dae-a74a-4d1d-9918-1a3bf4e68c23
		summarizeBy: none
		sourceColumn: seller_state

		annotation SummarizationSetBy = Automatic

	partition Sellers = m
		mode: import
		source =
				let
				    Zdroj = Csv.Document(File.Contents("C:\Users\marie\Documents\Datová analytika\brazilian e-commerce\olist_sellers_dataset.csv"),[Delimiter=",", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Záhlaví se zvýšenou úrovní" = Table.PromoteHeaders(Zdroj, [PromoteAllScalars=true]),
				    #"Změněný typ" = Table.TransformColumnTypes(#"Záhlaví se zvýšenou úrovní",{{"seller_id", type text}, {"seller_zip_code_prefix", Int64.Type}, {"seller_city", type text}, {"seller_state", type text}})
				in
				    #"Změněný typ"

	changedProperty = Name

	annotation PBI_ResultType = Table

